# Generated by Django 3.2.4 on 2021-06-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.kindpng.com%2Fimgv%2FiihmoJi_alt-text-placeholder-convenience-food-hd-png-download%2F&psig=AOvVaw0o61H0fg2Y379wDgL5LqxR&ust=1623685451027000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCKju7er5lPECFQAAAAAdAAAAABAI', max_length=1000),
        ),
    ]
