# Generated by Django 3.2.4 on 2021-06-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
